name: Sync Fork

on:
  workflow_dispatch: # on button click

jobs:
  sync:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          owner: PyDMD
          base: master
          head: master
          personal_token: ${{ secrets.NDEMO_TOKEN }}
          auto_approve: true
          ignore_fail: true
          merge_method: rebase
